name: mobili
description: Application voyageur Mobili — transport Afrique
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # ── Navigation ──────────────────────────────────────────────
  go_router: ^13.2.0

  # ── State management ────────────────────────────────────────
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # ── HTTP + cookies (refresh token httpOnly) ──────────────────
  dio: ^5.4.3
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

  # ── Cache local / offline-first ──────────────────────────────
  hive_flutter: ^1.1.0

  # ── Sécurité : stockage token access JWT ─────────────────────
  flutter_secure_storage: ^9.0.0

  # ── Utilitaires ──────────────────────────────────────────────
  equatable: ^2.0.5              # value equality sur les modèles
  json_annotation: ^4.9.0        # sérialisation JSON
  path_provider: ^2.1.5          # chemin disque pour CookieJar / Hive
  connectivity_plus: ^6.0.3      # détection réseau (offline UX)
  intl: ^0.19.0                  # formatage dates ISO 8601
   # ── UI / design ──────────────────────────────────────────────
  google_fonts: ^6.2.1

  url_launcher: ^6.3.0
  image_picker: ^1.2.2
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  share_plus: ^12.0.2
  app_links: ^7.1.1
  webview_flutter: ^4.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

  # ── Génération de code ───────────────────────────────────────
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1

  # ── Icônes et Splash Screen ──────────────────────────────────
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

# ── Configuration des Packages ─────────────────────────────────
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/app_icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#F5C400"
  adaptive_icon_foreground: "assets/icons/app_icon.jpeg"

flutter_native_splash:
  color: "#F5C400"
  image: "assets/icons/app_icon.jpeg"
  fullscreen: true
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/app_icon.jpeg # On déclare explicitement votre nouvelle icône ici
  fonts: []
  # Ajouter les polices ici si nécessaire
