-- Schéma de référence Mobili (idempotent, sans effacement de données).
-- Sur une base déjà remplie : CREATE IF NOT EXISTS ne fait rien (tables déjà là).
-- Les blocs DO en fin de fichier ajustent colonnes / contraintes sur des bases héritées d’Hibernate.
-- Règles de nommage : Spring PhysicalNaming (camelCase -> snake_case) sauf noms explicites @Column.

-- --- Noyau rôles / utilisateurs / partenaires / gares --------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    timestamp NOT NULL,
  name          varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
  id                                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at                          timestamp NOT NULL,
  firstname                           varchar(255),
  lastname                            varchar(255),
  login                               varchar(255) NOT NULL UNIQUE,
  email                               varchar(255) NOT NULL UNIQUE,
  password                            varchar(255) NOT NULL,
  avatar_url                          varchar(255),
  enabled                             boolean NOT NULL DEFAULT true,
  balance                             double precision DEFAULT 0.0,
  station_id                          bigint,
  covoiturage_id_front_url            varchar(255),
  covoiturage_id_back_url            varchar(255),
  covoiturage_id_valid_until          date,
  covoiturage_kyc_status              varchar(32),
  covoiturage_vehicle_brand           varchar(255),
  covoiturage_vehicle_plate           varchar(255),
  covoiturage_vehicle_color           varchar(255),
  covoiturage_grey_card_number        varchar(255),
  covoiturage_vehicle_photo_url       varchar(255),
  covoiturage_kyc_expiring_notified_for date,
  covoiturage_kyc_expired_notified   boolean,
  covoiturage_solo_profile            boolean
);

CREATE TABLE IF NOT EXISTS user_roles (
  user_id bigint NOT NULL,
  role_id bigint NOT NULL,
  PRIMARY KEY (user_id, role_id),
  CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS partners (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at             timestamp NOT NULL,
  name                   varchar(255) NOT NULL,
  email                  varchar(255) NOT NULL,
  logo_url               varchar(255),
  business_number        varchar(255),
  phone                  varchar(255),
  enabled                boolean NOT NULL DEFAULT true,
  registration_code      varchar(12) UNIQUE,
  user_id                bigint UNIQUE,
  covoiturage_solo_pool  boolean NOT NULL DEFAULT false,
  CONSTRAINT fk_partners_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS stations (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         timestamp NOT NULL,
  name               varchar(255) NOT NULL,
  city               varchar(255) NOT NULL,
  code               varchar(255),
  approval_status    varchar(20),
  active             boolean NOT NULL DEFAULT true,
  validated          boolean,
  partner_id         bigint NOT NULL,
  CONSTRAINT fk_stations_partner FOREIGN KEY (partner_id) REFERENCES partners (id)
);

DO $c$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_station') THEN
    IF EXISTS (SELECT 1 FROM information_schema.tables
               WHERE table_schema = current_schema() AND table_name = 'stations')
       AND EXISTS (SELECT 1 FROM information_schema.columns
                  WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'station_id') THEN
      ALTER TABLE users
        ADD CONSTRAINT fk_users_station FOREIGN KEY (station_id) REFERENCES stations (id);
    END IF;
  END IF;
END
$c$;

-- --- Trajets et segments -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trips (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at                timestamp NOT NULL,
  departure_city            varchar(255) NOT NULL,
  arrival_city              varchar(255) NOT NULL,
  boarding_point            varchar(255),
  vehicle_plate_number      varchar(255) NOT NULL,
  vehicle_image_url         varchar(255),
  departure_date_time       timestamp NOT NULL,
  price                     double precision NOT NULL,
  origin_destination_price  double precision,
  total_seats               integer NOT NULL,
  available_seats           integer NOT NULL,
  status                    varchar(255),
  stops_cities              text,
  vehicle_type              varchar(40) NOT NULL,
  transport_type            varchar(32) NOT NULL DEFAULT 'PUBLIC',
  partner_id                bigint NOT NULL,
  station_id                bigint,
  covoiturage_organizer_id  bigint,
  CONSTRAINT fk_trips_partner FOREIGN KEY (partner_id) REFERENCES partners (id),
  CONSTRAINT fk_trips_station FOREIGN KEY (station_id) REFERENCES stations (id),
  CONSTRAINT fk_trips_covoiturage_organizer FOREIGN KEY (covoiturage_organizer_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS trip_stops (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            timestamp NOT NULL,
  trip_id               bigint NOT NULL,
  stop_index            integer NOT NULL,
  city_label            varchar(120) NOT NULL,
  planned_departure_at  timestamp NOT NULL,
  CONSTRAINT fk_trip_stops_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

CREATE TABLE IF NOT EXISTS trip_stop_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamp NOT NULL,
  trip_id      bigint NOT NULL,
  stop_index   integer NOT NULL,
  event_type   varchar(40) NOT NULL,
  recorded_at  timestamp NOT NULL,
  CONSTRAINT fk_trip_stop_events_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

CREATE TABLE IF NOT EXISTS trip_segment_fares (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamp NOT NULL,
  trip_id           bigint NOT NULL,
  from_stop_index   integer NOT NULL,
  to_stop_index     integer NOT NULL,
  price             double precision NOT NULL,
  CONSTRAINT fk_trip_segment_fares_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

-- --- Réservations / billets --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at            timestamp NOT NULL,
  reference             varchar(255) NOT NULL UNIQUE,
  user_id               bigint NOT NULL,
  trip_id               bigint NOT NULL,
  number_of_seats      integer NOT NULL,
  total_price           double precision NOT NULL,
  status                varchar(32) NOT NULL,
  booking_date          timestamp,
  paid_at               timestamp,
  fedapay_transaction_id varchar(64),
  boarding_stop_index  integer,
  alighting_stop_index  integer,
  CONSTRAINT fk_bookings_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_bookings_trip FOREIGN KEY (trip_id) REFERENCES trips (id)
);

CREATE TABLE IF NOT EXISTS booking_passenger_names (
  booking_id     bigint NOT NULL,
  passenger_name varchar(255),
  CONSTRAINT fk_bpn_booking FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

CREATE TABLE IF NOT EXISTS booking_seat_numbers (
  booking_id   bigint NOT NULL,
  seat_number  varchar(255),
  CONSTRAINT fk_bsn_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tickets (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at              timestamp NOT NULL,
  ticket_number           varchar(255) NOT NULL UNIQUE,
  user_id                 bigint NOT NULL,
  passenger_name          varchar(255) NOT NULL,
  trip_id                 bigint NOT NULL,
  booking_date            timestamp NOT NULL,
  amount_paid             double precision NOT NULL,
  status                  varchar(32),
  booking_id              bigint NOT NULL,
  seat_number             varchar(255) NOT NULL,
  scanned                 boolean NOT NULL DEFAULT false,
  scanned_at              timestamp,
  boarding_stop_index     integer,
  alighting_stop_index    integer,
  alighted_at_stop_index  integer,
  alighted_at             timestamp,
  CONSTRAINT fk_tickets_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_tickets_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_tickets_booking FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

-- --- Messagerie / notifications ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trip_channel_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NOT NULL,
  trip_id    bigint NOT NULL,
  author_id  bigint NOT NULL,
  body       varchar(2000) NOT NULL,
  CONSTRAINT fk_tcm_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_tcm_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS partner_gare_com_threads (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         timestamp NOT NULL,
  partner_id         bigint NOT NULL,
  scope              varchar(20) NOT NULL,
  title              varchar(200) NOT NULL,
  last_activity_at   timestamp NOT NULL,
  CONSTRAINT fk_pgct_partner FOREIGN KEY (partner_id) REFERENCES partners (id)
);

CREATE TABLE IF NOT EXISTS partner_gare_com_messages (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NOT NULL,
  thread_id  bigint NOT NULL,
  author_id  bigint NOT NULL,
  body       varchar(4000) NOT NULL,
  CONSTRAINT fk_pgcm_thread FOREIGN KEY (thread_id) REFERENCES partner_gare_com_threads (id),
  CONSTRAINT fk_pgcm_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS partner_gare_com_thread_targets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at  timestamp NOT NULL,
  thread_id   bigint NOT NULL,
  station_id  bigint NOT NULL,
  CONSTRAINT uk_pgctt_thread_station UNIQUE (thread_id, station_id),
  CONSTRAINT fk_pgctt_thread FOREIGN KEY (thread_id) REFERENCES partner_gare_com_threads (id),
  CONSTRAINT fk_pgctt_station FOREIGN KEY (station_id) REFERENCES stations (id)
);

CREATE TABLE IF NOT EXISTS mobili_inbox_notifications (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at                  timestamp NOT NULL,
  user_id                     bigint NOT NULL,
  type                        varchar(40) NOT NULL,
  title                       varchar(300) NOT NULL,
  body                        varchar(2000) NOT NULL,
  trip_id                     bigint,
  channel_message_id         bigint,
  partner_gare_com_thread_id  bigint,
  read_at                    timestamp,
  CONSTRAINT fk_inbox_user FOREIGN KEY (user_id) REFERENCES users (id),
  CONSTRAINT fk_inbox_trip FOREIGN KEY (trip_id) REFERENCES trips (id),
  CONSTRAINT fk_inbox_channel_msg FOREIGN KEY (channel_message_id) REFERENCES trip_channel_messages (id),
  CONSTRAINT fk_inbox_pgct FOREIGN KEY (partner_gare_com_thread_id) REFERENCES partner_gare_com_threads (id)
);

-- --- Divers --------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_analytics_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp NOT NULL,
  event_type varchar(40) NOT NULL,
  user_id    bigint,
  payload    varchar(2000)
);

CREATE TABLE IF NOT EXISTS login_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL,
  login      varchar(255) NOT NULL,
  login_time timestamp NOT NULL,
  login_date date NOT NULL
);

-- Colonne transport_type sur bases héritées (nullable ou absente) + backfill (équ. TransportTypeDefaultMigration)
DO $tr$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_schema = current_schema() AND table_name = 'trips') THEN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = current_schema() AND table_name = 'trips' AND column_name = 'transport_type') THEN
      ALTER TABLE trips ADD COLUMN transport_type varchar(32) DEFAULT 'PUBLIC';
    END IF;
    UPDATE trips SET transport_type = 'PUBLIC' WHERE transport_type IS NULL;
    ALTER TABLE trips ALTER COLUMN transport_type SET DEFAULT 'PUBLIC';
    IF NOT EXISTS (SELECT 1 FROM trips WHERE transport_type IS NULL) THEN
      ALTER TABLE trips ALTER COLUMN transport_type SET NOT NULL;
    END IF;
  END IF;
END
$tr$;

-- Contraintes CHECK (alignement enums Java) — s’applique aux bases existantes dès l’arrivée de V2
DO $chk1$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_schema = current_schema() AND table_name = 'trips') THEN
    ALTER TABLE trips DROP CONSTRAINT IF EXISTS trips_vehicle_type_check;
    ALTER TABLE trips
      ADD CONSTRAINT trips_vehicle_type_check
      CHECK (vehicle_type IN (
        'BUS_CLIMATISE', 'BUS_CLASSIQUE', 'CAR_70_PLACES', 'MINIBUS',
        'MASSA_NORMAL', 'MASSA_6_ROUES', 'VAN',
        'SUV', 'BERLINE', 'CITADINE', 'MONOSPACE', 'PICKUP'));
  END IF;
END
$chk1$;

DO $chk2$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables
             WHERE table_schema = current_schema() AND table_name = 'mobili_inbox_notifications') THEN
    ALTER TABLE mobili_inbox_notifications DROP CONSTRAINT IF EXISTS mobili_inbox_notifications_type_check;
    ALTER TABLE mobili_inbox_notifications
      ADD CONSTRAINT mobili_inbox_notifications_type_check
      CHECK (type IN (
        'TICKET_ISSUED', 'TRIP_CHANNEL_MESSAGE', 'PARTNER_NEW_BOOKING',
        'GARE_STATION_NEW_BOOKING', 'PARTNER_GARE_COM_MESSAGE',
        'COV_KYC_EXPIRING_SOON', 'COV_KYC_EXPIRED'));
  END IF;
END
$chk2$;
