name: Cd Pipeline Mobili
on: 
  push:
    branches:
      - main
      - 'feature/**' # Déclenche le pipeline pour les branches de fonctionnalités
      - 'develop' # Déclenche le pipeline pour la branche de développement
    paths-ignore:
      - 'README.md' # Ignore les changements sur le README
      - 'docs/**' # Ignore les changements dans le dossier docs  
      - '.github/workflows/**' # Ignore les changements dans les workflows GitHub Actions
  workflow_dispatch: # Permet de déclencher manuellement le workflow depuis l'interface GitHub
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4 est la version stable actuelle
      
      - name: setup node js ans install dependencies
        uses: ./.github/actions/setupnode
      - name: Run tests
        run: |
          cd frontend
          npm test -- --watch=false

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node js ans install dependencies
        uses: ./.github/actions/setupnode
        with:
          node-version: '20' # Spécifie la version de Node.js à utiliser pour le build

      - name: Build application
        run: |
          cd frontend
          npm run build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: frontend/dist # Assure-toi que c'est le bon chemin vers tes fichiers buildés

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: frontend/dist
      - name: Deploy to server
        run: echo "Déploiement de l'application sur le serveur de production OK"
