name: Cd Pipeline Mobili 
on: push
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
          - name: 👋 Initialisation
            run: |
                echo clone du repo
                echo "${{toJson(github)}}"
                git clone https://github.com/${{github.repository}}.git MesFichiers
                cd MesFichiers && ls